// Keep DOM lookups in one place so feature code can stay focused on behavior.
export const elements = {
  caseForm: document.querySelector("#caseForm"),
  caseFormPanel: document.querySelector("#caseFormPanel"),
  caseFormTitle: document.querySelector("#caseFormTitle"),
  caseSubmitButton: document.querySelector("#caseSubmitButton"),
  cancelCaseEditButton: document.querySelector("#cancelCaseEditButton"),
  createCaseButton: document.querySelector("#createCaseButton"),
  addStepButton: document.querySelector("#addStepButton"),
  caseStepRows: document.querySelector("#caseStepRows"),
  categoryForm: document.querySelector("#categoryForm"),
  categoryName: document.querySelector("#categoryName"),
  categoryTree: document.querySelector("#categoryTree"),
  suiteList: document.querySelector("#suiteList"),
  suiteCount: document.querySelector("#suiteCount"),
  suiteSearch: document.querySelector("#suiteSearch"),
  clearSuiteSearchButton: document.querySelector("#clearSuiteSearchButton"),
  suiteForm: document.querySelector("#suiteForm"),
  suiteFormTitle: document.querySelector("#suiteFormTitle"),
  suiteSubmitButton: document.querySelector("#suiteSubmitButton"),
  cancelSuiteEditButton: document.querySelector("#cancelSuiteEditButton"),
  deleteSuiteButton: document.querySelector("#deleteSuiteButton"),
  suiteName: document.querySelector("#suiteName"),
  suiteDescription: document.querySelector("#suiteDescription"),
  suiteCaseSearch: document.querySelector("#suiteCaseSearch"),
  suiteCaseCategoryFilter: document.querySelector("#suiteCaseCategoryFilter"),
  suiteCaseChecklist: document.querySelector("#suiteCaseChecklist"),
  selectedSuiteCaseCount: document.querySelector("#selectedSuiteCaseCount"),
  suiteDetailEmpty: document.querySelector("#suiteDetailEmpty"),
  caseDetailEmpty: document.querySelector("#caseDetailEmpty"),
  caseDetailContent: document.querySelector("#caseDetailContent"),
  selectedCaseTitle: document.querySelector("#selectedCaseTitle"),
  selectedCasePriority: document.querySelector("#selectedCasePriority"),
  caseDetailBody: document.querySelector("#caseDetailBody"),
  editSelectedCaseButton: document.querySelector("#editSelectedCaseButton"),
  duplicateSelectedCaseButton: document.querySelector("#duplicateSelectedCaseButton"),
  deleteSelectedCaseButton: document.querySelector("#deleteSelectedCaseButton"),
  restoreSelectedCaseButton: document.querySelector("#restoreSelectedCaseButton"),
  executionForm: document.querySelector("#executionForm"),
  executionPageRoot: document.querySelector("#executionPageRoot"),
  executionCreatorPane: document.querySelector("#executionCreatorPane"),
  toggleExecutionCreatorButton: document.querySelector("#toggleExecutionCreatorButton"),
  closeExecutionCreatorButton: document.querySelector("#closeExecutionCreatorButton"),
  caseSearch: document.querySelector("#caseSearch"),
  casePriorityFilter: document.querySelector("#casePriorityFilter"),
  showRetiredCasesToggle: document.querySelector("#showRetiredCasesToggle"),
  clearCaseFiltersButton: document.querySelector("#clearCaseFiltersButton"),
  caseCsvFile: document.querySelector("#caseCsvFile"),
  downloadCsvTemplateButton: document.querySelector("#downloadCsvTemplateButton"),
  previewCsvButton: document.querySelector("#previewCsvButton"),
  confirmCsvImportButton: document.querySelector("#confirmCsvImportButton"),
  cancelCsvPreviewButton: document.querySelector("#cancelCsvPreviewButton"),
  cancelCsvPreviewFooterButton: document.querySelector("#cancelCsvPreviewFooterButton"),
  csvPreviewModal: document.querySelector("#csvPreviewModal"),
  csvPreviewPanel: document.querySelector("#csvPreviewPanel"),
  csvImportActions: document.querySelector("#csvImportActions"),
  executionList: document.querySelector("#executionList"),
  executionSearch: document.querySelector("#executionSearch"),
  clearExecutionSearchButton: document.querySelector("#clearExecutionSearchButton"),
  caseCount: document.querySelector("#caseCount"),
  executionCount: document.querySelector("#executionCount"),
  executionCaseSearch: document.querySelector("#executionCaseSearch"),
  executionSuiteSelect: document.querySelector("#executionSuiteSelect"),
  applyExecutionSuiteButton: document.querySelector("#applyExecutionSuiteButton"),
  executionCaseCategoryFilter: document.querySelector("#executionCaseCategoryFilter"),
  executionCaseChecklist: document.querySelector("#executionCaseChecklist"),
  selectedCaseCount: document.querySelector("#selectedCaseCount"),
  addCaseSearch: document.querySelector("#addCaseSearch"),
  addCaseCategoryFilter: document.querySelector("#addCaseCategoryFilter"),
  addCaseChecklist: document.querySelector("#addCaseChecklist"),
  selectedAddCaseCount: document.querySelector("#selectedAddCaseCount"),
  addSelectedCasesButton: document.querySelector("#addSelectedCasesButton"),
  showExecutionSummaryButton: document.querySelector("#showExecutionSummaryButton"),
  summaryShortcutMeta: document.querySelector("#summaryShortcutMeta"),
  bulkResultStatus: document.querySelector("#bulkResultStatus"),
  bulkResultNotes: document.querySelector("#bulkResultNotes"),
  applyBulkResultButton: document.querySelector("#applyBulkResultButton"),
  clearBulkSelectionButton: document.querySelector("#clearBulkSelectionButton"),
  selectedResultCount: document.querySelector("#selectedResultCount"),
  selectedExecutionItemTitle: document.querySelector("#selectedExecutionItemTitle"),
  selectedExecutionItemMeta: document.querySelector("#selectedExecutionItemMeta"),
  selectedExecutionItemBody: document.querySelector("#selectedExecutionItemBody"),
  selectedExecutionItemForm: document.querySelector("#selectedExecutionItemForm"),
  selectedExecutionItemStatus: document.querySelector("#selectedExecutionItemStatus"),
  selectedExecutionItemActualResult: document.querySelector(
    "#selectedExecutionItemActualResult"
  ),
  historyList: document.querySelector("#historyList"),
  detailPanel: document.querySelector("#executionDetailPanel"),
  executionEmptyPanel: document.querySelector("#executionEmptyPanel"),
  selectedExecutionLabel: document.querySelector("#selectedExecutionLabel"),
  exportExecutionReportButton: document.querySelector("#exportExecutionReportButton"),
  deleteExecutionButton: document.querySelector("#deleteExecutionButton"),
  toast: document.querySelector("#toast"),
};

export const hasExecutionPage = Boolean(
  elements.executionForm || elements.executionList || elements.detailPanel
);

export const hasSuitePage = Boolean(elements.suiteForm || elements.suiteList);
